name: Test

on: [push]

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@1.3.7
        with:
          php-version: 7.4
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-suggest
      - name: Run tests
        run: |
          composer run test