name: Lint and test

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.php'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.php'

concurrency:
  # Cancel previous runs of this workflow if they are testing the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3']
        os: [ubuntu-latest]
#        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    name: PHP tests ${{ matrix.php }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, phive
          extensions: fileinfo

      - name: Install Phive tools
        uses: ngmy/phive-install-action@master

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Build phar
        run:
          ./scripts/createphar.sh

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.php == '7.4' && github.event_name == 'pull_request' }}
        id: artifact-upload-step
        with:
          name: strauss.phar
          path: strauss.phar

      - name: Add phar to PR comment
        uses: mshick/add-pr-comment@v2
        if: ${{ matrix.php == '7.4' && github.event_name == 'pull_request' }}
        with:
          message-id: strauss-phar
          message: ${{ format('[strauss.phar.zip]({0}) @{1}', steps.artifact-upload-step.outputs.artifact-url, github.event.pull_request.head.sha) }}

      - name: Run tests with strauss.phar
        run: vendor/bin/phpunit

        # TODO: get GitHub Actions annotations working again.
#        run: vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer
  lint:
    runs-on: ubuntu-latest
    name: Lint project files
    steps:

      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, cs2pr, phive

      - name: Install Phive tools
        uses: ngmy/phive-install-action@master

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run validate
        run: |
          vendor/bin/phpcbf || true
          vendor/bin/phpcs -q -n --report=checkstyle | cs2pr

      - name: Commit PHPCBF changes
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # only commit on pushes to master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 PHPCBF"
