name: Build and attach Mozart.phar to each release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  create-phar:
    runs-on: ubuntu-latest
    name: Create Mozart phar
    steps:
      - uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@1.3.7
        with:
          php-version: 7.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: Create .phar
        run: |
          vendor/bin/phar-composer build .

      - name: Attach file to release
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'mozart.phar'
          file: 'mozart.phar'